name: Android CI/CD

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app/google-services.json

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      # Даем права на выполнение Gradle
      - name: Make gradlew executable
        run: chmod +x gradlew

      # 1. Запуск Detekt
      - name: Run Detekt
        run: ./gradlew detekt

      # 2. Запуск Unit-тестов
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # Сборка APK (необходима для загрузки)
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # 3. Загрузка в Firebase App Distribution
      - name: Upload to Firebase App Distribution
        uses: w9jds/firebase-action@master
        with:
          args: appdistribution:distribute app/build/outputs/apk/debug/app-debug.apk --app ${{ secrets.FIREBASE_APP_ID }} --groups "qa-team"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}